services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA:-Y}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - is-network

  app:
    image: isapp:lab8
    container_name: isapp
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://0.0.0.0:8080}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - App__Name=${App__Name:-IsLabApp}
      - App__Version=${App__Version:-0.1.0-lab8}
      - ConnectionStrings__Mssql=${ConnectionStrings__Mssql}
    ports:
      - "127.0.0.1:5001:8080"
    networks:
      - is-network
    depends_on:
      - mssql

volumes:
  mssql-data:

networks:
  is-network:
